[gcp_service_account]
type = "service_account"
project_id = "SEU_PROJECT_ID"
private_key_id = "SUA_PRIVATE_KEY_ID"
private_key = """-----BEGIN PRIVATE KEY-----
COLE_AQUI
-----END PRIVATE KEY-----
"""
client_email = "NOME@SEU-PROJETO.iam.gserviceaccount.com"
client_id = "SEU_CLIENT_ID"
token_uri = "https://oauth2.googleapis.com/token"

[drive]
folder_id = "1fHtt2LWw0SRx8EUemXHoZQWd0lw3wZXe"

[github]
token = "ghp_SEU_TOKEN"
repo = "usuario/repositorio"
branch = "main"
base_path = "reports"
