[gcp_service_account]
type = "service_account"
project_id = "rdna-461214"
private_key_id = """352ca5cd245ec8eb63229e20f1f0ce47d6dd41b9""
private_key = """-----BEGIN PRIVATE KEY-----
COLE_AQUI_TUDO_DO_JSON
-----END PRIVATE KEY-----
"""
client_email = "streamlit-drive@rdna-461214.iam.gserviceaccount.com"
client_id = "COLE_DO_JSON"
token_uri = "https://oauth2.googleapis.com/token"

[drive]
folder_id = "1fHtt2LWw0SRx8EUemXHoZQWd0lw3wZXe"
